### ISSUE TITLE
Consider moving documentation into this repository

### ISSUE THREAD

**Issue by LinguineCode** [puppetinabox/controlrepo#22]
Documentation for this repo is separated into another repo here: https://github.com/puppetinabox/documentation. I propose moving documentation into this repo.

I said on IRC:

> it may not be intuitive for someone to search through your list of repos and click on the one named "documentation".  also personally i would prefer not having to switch back/forth, would you consider putting the README.md in the controlrepo?  maybe under docs/ subfolder?

I will submit a PR

**Comment by rnelson0** [comment]
@seanscottking I think I'll add this to the Wiki portion of the GH repo, so that way it's not deployed with the branches. In addition I'll craft a README.md (drafting it at https://github.com/puppetinabox/controlrepo/tree/readme) that is available on disk, but I'll keep that trim.

**Comment by LinguineCode** [comment]
That sounds great. I never used a GitHub Wiki. They have a list of excellent examples [here](https://github.com/showcases/projects-with-great-wikis). One in particular that I liked is [here](https://github.com/guard/guard/wiki).

I can spend some time getting familiar with the Wiki service and convert https://github.com/puppetinabox/documentation. I wonder if I need certain permissions on the project to do that? I guess we will find out

**Comment by rnelson0** [comment]
@seanscottking I have set up the initial wiki pages. It's kinda rough on an iPad though, it will need some more edits.

I'll also add you to the wiki as an editor when I figure out how, it's new to me as well. Feel free to help with the tidy up and we can discuss more significant issues in this ticket.

**Comment by rnelson0** [comment]
Well, yay, everyone already has access to submit edits! I can restrict it if necessary, but let's hope that is never the case.

**Comment by rnelson0** [comment]
Ok, still some cleanup to do but I'm done with the overall layout. Let me know what you think @seanscottking

**Comment by rnelson0** [comment]
@seanscottking I think the wiki is complete and I moved all the issues that were still open and valid from documentation. Unless you say otherwise, I'll close this out in a few days and get rid of the documentation repo.

**Comment by LinguineCode** [comment]
Damnnn that's a good lookin' Wiki. Now all we need is a `README.md`, possibly with a visual pointer that says "go to the wiki", and we're all set

Anything I can do to help?  What do you want to cover in the `README.md` ?

**Comment by rnelson0** [comment]
I think a quick summary and a pointer to the read me will suffice - no
point in putting the same info in two places or it will just get out of
sync.

On Friday, August 14, 2015, Sean S. King notifications@github.com wrote:

> Damnnn that's a good lookin' Wiki. Now all we need is a README.md,
> possibly with a visual pointer that says "go to the wiki", and we're all set
> 
> Anything I can do to help? What do you want to cover in the README.md ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/puppetinabox/controlrepo/issues/22#issuecomment-131128562
> .

## 

Rob Nelson
rnelson0@gmail.com

**Comment by LinguineCode** [comment]
Got it, will report back by the weekend

**Comment by rnelson0** [comment]
@seanscottking Thanks a lot for this! Between the wiki and the README this covers the general documentation issue. I'll mark the old documentation repo for deletion in a few weeks, just in case.
